# 12-1 pandas의 1차원 자료형 - series
1차원적인 데이터 형식\
파이썬의 딕셔너리와 유사함

In [2]:
import pandas as pd

In [3]:
a = {'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}

In [4]:
a

{'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}

In [5]:
type(a)

dict

In [6]:
#딕셔너리를 pandas의 series 형태로 출력
b = pd.Series(a)

In [7]:
b

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [8]:
type(b)

pandas.core.series.Series

In [9]:
b.shape

(5,)

In [10]:
#numpy 구조 활용
import numpy as np

In [11]:
aa = np.arange(3,10)

In [12]:
aa

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
#index가 없으므로 자동으로 0부터 나온다.
bb = pd.Series(aa)

In [14]:
bb

0    3
1    4
2    5
3    6
4    7
5    8
6    9
dtype: int32

In [15]:
bb.shape

(7,)

In [16]:
#딕셔너리에서 키 혹은 값만 뽑아서 출력
a

{'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}

In [17]:
a.keys()

dict_keys(['a', 'b', 'c', 'd', 'e'])

In [18]:
a.values()

dict_values([10, 20, 30, 40, 50])

In [19]:
#시리즈에서는 index, velues이다.
b

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [20]:
b.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [21]:
b.values

array([10, 20, 30, 40, 50], dtype=int64)

In [22]:
#리스트를 시리즈로 만들기
c = [10,20,30,40,50]

In [23]:
d = pd.Series(c)

In [24]:
d

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [25]:
type(d)

pandas.core.series.Series

In [26]:
d.shape

(5,)

In [27]:
d.index

RangeIndex(start=0, stop=5, step=1)

In [28]:
d.values

array([10, 20, 30, 40, 50], dtype=int64)

In [29]:
#index에 이름을 지정하기
e = ['a', 'b', 'c', 'd', 'e']
f = [10,20,30,40,50]

In [30]:
#series()안에 들어가는 건 values, index 순서이다.
g = pd.Series(f, index=e)

In [31]:
g

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [32]:
#index로 접근할 때 인덱스의 이름, 인덱스 값 둘 다 가능
g['a']

10

In [33]:
g[0]

10

In [34]:
#위치 정보가 아니라면 끝자리를 포함한다.(loc함수와 비슷한 듯?)
g['a':'d']

a    10
b    20
c    30
d    40
dtype: int64

In [35]:
#위치 정보로 접근했으므로 끝자리를 비포함한다.(iloc함수?)
g[0:4]

a    10
b    20
c    30
d    40
dtype: int64

12-2 pandas의 2차원 자료형 - DataFrame 1\
\
2차원적인 데이터 형식\
행렬 구조를 가짐

In [36]:
import pandas as pd

In [37]:
#딕셔너리 각각 키의 값이 1차원 리스트로 되어 있다.
a = {'a': [1,2,3], 'b':[1,3,5], 'c':[2,4,6], 'd':[3,6,9]}

In [38]:
a

{'a': [1, 2, 3], 'b': [1, 3, 5], 'c': [2, 4, 6], 'd': [3, 6, 9]}

In [39]:
#딕셔너리를 pandas의 dataframe 구조로 옮기기
df1 = pd.DataFrame(a)

In [40]:
df1

a  b  c  d
0  1  1  2  3
1  2  3  4  6
2  3  5  6  9

In [41]:
type(df1)

pandas.core.frame.DataFrame

In [42]:
df1.shape

(3, 4)

In [43]:
#info: 각각의 컬럼별로 속성과 데이터타입을 요약해서 출력
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      int64
 1   b       3 non-null      int64
 2   c       3 non-null      int64
 3   d       3 non-null      int64
dtypes: int64(4)
memory usage: 224.0 bytes


In [44]:
#numpy 활용
import numpy as np

In [45]:
b = np.arange(12).reshape(3,4)

In [46]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
df2 = pd.DataFrame(b)

In [48]:
df2

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [49]:
type(df2)

pandas.core.frame.DataFrame

In [50]:
df2.shape

(3, 4)

In [51]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       3 non-null      int32
 1   1       3 non-null      int32
 2   2       3 non-null      int32
 3   3       3 non-null      int32
dtypes: int32(4)
memory usage: 176.0 bytes


In [52]:
#바로 데이터프레임으로 만들기
df = pd.DataFrame([[1, 20, '서울'], [2, 25, '대전']],
                 index = ['홍길동', '홍길순'],
                 columns = ['순서', '나이', '지역'])

In [53]:
df

순서  나이  지역
홍길동   1  20  서울
홍길순   2  25  대전

In [54]:
type(df)

pandas.core.frame.DataFrame

In [55]:
df.shape

(2, 3)

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, 홍길동 to 홍길순
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   순서      2 non-null      int64 
 1   나이      2 non-null      int64 
 2   지역      2 non-null      object
dtypes: int64(2), object(1)
memory usage: 64.0+ bytes


In [57]:
#index, columns, values 뽑아 출력하기
df.index

Index(['홍길동', '홍길순'], dtype='object')

In [58]:
df.columns

Index(['순서', '나이', '지역'], dtype='object')

In [59]:
df.values

array([[1, 20, '서울'],
       [2, 25, '대전']], dtype=object)

In [60]:
#index 바꾸기
df.index = ['사람1', '사람2']

In [61]:
df

순서  나이  지역
사람1   1  20  서울
사람2   2  25  대전

In [62]:
#columns 바꾸기
df.columns = ['연번', '연령', '도시']

In [63]:
df

연번  연령  도시
사람1   1  20  서울
사람2   2  25  대전

In [64]:
#위처럼 통째로 바꾸는 것이 아니라면 rename함수 활용
#특정 인덱스만 바꾸기
df = df.rename(index = {'사람1': '홍길동'})

In [65]:
df

연번  연령  도시
홍길동   1  20  서울
사람2   2  25  대전

In [66]:
#특정 컬럼만 바꾸기
df = df.rename(columns = {'연번': '순서', '연령': '나이'})

In [67]:
df

순서  나이  도시
홍길동   1  20  서울
사람2   2  25  대전

12-3 pandas의 2차원 자료형 - DataFrame 2\
\
행 추가\
열 추가\
값 변경\
행 삭제\
열 삭제

In [68]:
df

순서  나이  도시
홍길동   1  20  서울
사람2   2  25  대전

In [69]:
#행 추가
df.loc['사람3'] = [3, 30, '부산']
df

순서  나이  도시
홍길동   1  20  서울
사람2   2  25  대전
사람3   3  30  부산

In [70]:
#값을 전부 0으로 채우기
df.loc['사람4'] = 0

In [71]:
df

순서  나이  도시
홍길동   1  20  서울
사람2   2  25  대전
사람3   3  30  부산
사람4   0   0   0

In [72]:
#기존 행의 값 복사해서 만들기
df.loc['사람1'] = df.loc['홍길동']
df

순서  나이  도시
홍길동   1  20  서울
사람2   2  25  대전
사람3   3  30  부산
사람4   0   0   0
사람1   1  20  서울

In [73]:
#열 추가
df['나이대'] = ['20대', '20대', '30대', '0', '20대']
df

순서  나이  도시  나이대
홍길동   1  20  서울  20대
사람2   2  25  대전  20대
사람3   3  30  부산  30대
사람4   0   0   0    0
사람1   1  20  서울  20대

In [75]:
#전부 동일한 값으로 채우기
df['직업'] = '학생'
df

순서  나이  도시  나이대  직업
홍길동   1  20  서울  20대  학생
사람2   2  25  대전  20대  학생
사람3   3  30  부산  30대  학생
사람4   0   0   0    0  학생
사람1   1  20  서울  20대  학생

In [76]:
#값 변경
df.loc['사람4', '순서'] = 4
df

순서  나이  도시  나이대  직업
홍길동   1  20  서울  20대  학생
사람2   2  25  대전  20대  학생
사람3   3  30  부산  30대  학생
사람4   4   0   0    0  학생
사람1   1  20  서울  20대  학생

In [78]:
df.iloc[3, 1] = 10
df

순서  나이  도시  나이대  직업
홍길동   1  20  서울  20대  학생
사람2   2  25  대전  20대  학생
사람3   3  30  부산  30대  학생
사람4   4  10   0    0  학생
사람1   1  20  서울  20대  학생

In [79]:
#일괄 수정
df.loc['사람4', ['도시', '나이대']] = '광주', '10대'
df

순서  나이  도시  나이대  직업
홍길동   1  20  서울  20대  학생
사람2   2  25  대전  20대  학생
사람3   3  30  부산  30대  학생
사람4   4  10  광주  10대  학생
사람1   1  20  서울  20대  학생

In [80]:
df.iloc[3, [1, 3]] = 40, '40대'
df

순서  나이  도시  나이대  직업
홍길동   1  20  서울  20대  학생
사람2   2  25  대전  20대  학생
사람3   3  30  부산  30대  학생
사람4   4  40  광주  40대  학생
사람1   1  20  서울  20대  학생

In [81]:
#행 삭제 drop 사용(저장하려면 따로 변수에 지정해야 함)
#행 단위 삭제는 axis = 0, 열 단위 삭제는 axis = 1
df = df.drop('사람4', axis = 0)
df

순서  나이  도시  나이대  직업
홍길동   1  20  서울  20대  학생
사람2   2  25  대전  20대  학생
사람3   3  30  부산  30대  학생
사람1   1  20  서울  20대  학생

In [82]:
#열 삭제
df = df.drop(['나이대', '직업'], axis = 1)
df

순서  나이  도시
홍길동   1  20  서울
사람2   2  25  대전
사람3   3  30  부산
사람1   1  20  서울

12-4 pandas의 2차원 자료형 - DataFrame 3

In [83]:
#df 복사
df2 = df
df2

순서  나이  도시
홍길동   1  20  서울
사람2   2  25  대전
사람3   3  30  부산
사람1   1  20  서울

In [84]:
df2.loc['사람1', '순서'] = 4
df2

순서  나이  도시
홍길동   1  20  서울
사람2   2  25  대전
사람3   3  30  부산
사람1   4  20  서울

In [85]:
#기존 값도 함께 변경됨
df

순서  나이  도시
홍길동   1  20  서울
사람2   2  25  대전
사람3   3  30  부산
사람1   4  20  서울

In [87]:
#역시 copy함수 활용
df3 = df.copy()
df3

순서  나이  도시
홍길동   1  20  서울
사람2   2  25  대전
사람3   3  30  부산
사람1   4  20  서울

In [88]:
df3.loc['사람1', '순서'] = 5
df3

순서  나이  도시
홍길동   1  20  서울
사람2   2  25  대전
사람3   3  30  부산
사람1   5  20  서울

In [89]:
#원본이 바뀌지 않는다.
df

순서  나이  도시
홍길동   1  20  서울
사람2   2  25  대전
사람3   3  30  부산
사람1   4  20  서울

In [90]:
#특정 부분만 가져와서 저장
hong = df.loc['홍길동']
hong

순서     1
나이    20
도시    서울
Name: 홍길동, dtype: object

In [91]:
#시리즈 형태로 가져오게 된다.
type(hong)

pandas.core.series.Series

In [93]:
#1차원 형태이다.
hong.shape

(3,)

In [94]:
gil = df.iloc[0]
gil

순서     1
나이    20
도시    서울
Name: 홍길동, dtype: object

In [95]:
type(gil)

pandas.core.series.Series

In [96]:
gil.shape

(3,)

In [97]:
#여러 부분 가져오기
df4 = df.loc[['홍길동', '사람1']]
df4

순서  나이  도시
홍길동   1  20  서울
사람1   4  20  서울

In [98]:
#df 형태로 가져온다.
type(df4)

pandas.core.frame.DataFrame

In [99]:
#2차원 형태이다.
df4.shape

(2, 3)

In [101]:
df5 = df.iloc[[0, 3]]
df5

순서  나이  도시
홍길동   1  20  서울
사람1   4  20  서울

In [102]:
#범위 지정해서 가져오기
#loc는 끝자리 포함한다.
df6 = df.loc['홍길동':'사람3']
df6

순서  나이  도시
홍길동   1  20  서울
사람2   2  25  대전
사람3   3  30  부산

In [103]:
#iloc는 끝자리 미포함
df7 = df.iloc[0:3]
df7

순서  나이  도시
홍길동   1  20  서울
사람2   2  25  대전
사람3   3  30  부산

In [104]:
#원본 보존
df

순서  나이  도시
홍길동   1  20  서울
사람2   2  25  대전
사람3   3  30  부산
사람1   4  20  서울

In [105]:
#대괄호 두 개로 하면 df형태
df8 = df[['나이']]
df8

나이
홍길동  20
사람2  25
사람3  30
사람1  20

In [106]:
#대괄호 하나로 하면 시리즈 형태
df9 = df['나이']
df9

홍길동    20
사람2    25
사람3    30
사람1    20
Name: 나이, dtype: int64

In [107]:
type(df8)

pandas.core.frame.DataFrame

In [108]:
type(df9)

pandas.core.series.Series

In [109]:
df10 = df[['나이', '도시']]
df10

나이  도시
홍길동  20  서울
사람2  25  대전
사람3  30  부산
사람1  20  서울

In [110]:
#특정 컬럼, 인덱스만 가져오기
df11 = df.loc[['홍길동', '사람1'], ['나이', '도시']]
df11

나이  도시
홍길동  20  서울
사람1  20  서울

In [112]:
df12 = df.iloc[[0,3],[1,2]]
df12

나이  도시
홍길동  20  서울
사람1  20  서울

12-5 pandas의 2차원 자료형 - DataFrame 4\
\
인덱스\
정렬\
전치\
치환

In [140]:
a = {'이름': ['홍길동','사람1','사람2'], '나이':[20,30,25], '도시':['서울','서울','대전']}
a

{'이름': ['홍길동', '사람1', '사람2'], '나이': [20, 30, 25], '도시': ['서울', '서울', '대전']}

In [141]:
#인덱스 정보가 없으므로  default로 출력(0,1,2)
df = pd.DataFrame(a)
df

이름  나이  도시
0  홍길동  20  서울
1  사람1  30  서울
2  사람2  25  대전

In [142]:
#인덱스 지정 set_index 활용
df2 = df.set_index('이름')
df2

나이  도시
이름         
홍길동  20  서울
사람1  30  서울
사람2  25  대전

In [143]:
#set_index는 기존 인덱스를 날려버린다.
df3 = df2.set_index('도시')
df3

나이
도시    
서울  20
서울  30
대전  25

In [144]:
df2

나이  도시
이름         
홍길동  20  서울
사람1  30  서울
사람2  25  대전

In [145]:
#set_index를 원래대로 돌리기 reset_index
df3 = df2.reset_index()
df3

이름  나이  도시
0  홍길동  20  서울
1  사람1  30  서울
2  사람2  25  대전

In [146]:
df3 = df3.set_index('도시')
df3

이름  나이
도시         
서울  홍길동  20
서울  사람1  30
대전  사람2  25

In [147]:
#정렬
df2

나이  도시
이름         
홍길동  20  서울
사람1  30  서울
사람2  25  대전

In [148]:
#인덱스 기준 정렬 sort_index
#ascending=True이면 오름차순, False이면 내림차순 정렬
df2 = df2.sort_index(ascending = True)
df2

나이  도시
이름         
사람1  30  서울
사람2  25  대전
홍길동  20  서울

In [149]:
df2 = df2.sort_index(ascending = False)
df2

나이  도시
이름         
홍길동  20  서울
사람2  25  대전
사람1  30  서울

In [150]:
#컬럼 기준 정렬 sort_values(by=)
#by=컬럼
df2 = df2.sort_values(by = '나이', ascending=True)
df2

나이  도시
이름         
홍길동  20  서울
사람2  25  대전
사람1  30  서울

In [151]:
df2 = df2.sort_values(by='나이', ascending=False)
df2

나이  도시
이름         
사람1  30  서울
사람2  25  대전
홍길동  20  서울

In [152]:
#전치: 인덱스와 컬럼을 전치 T
df2 = df2.T
df2

이름 사람1 사람2 홍길동
나이  30  25  20
도시  서울  대전  서울

In [153]:
df2 = df2.T
df2

나이  도시
이름         
사람1  30  서울
사람2  25  대전
홍길동  20  서울

In [154]:
#치환
df2['나이대'] = ['30대', '20대', '20대']
df2

나이  도시  나이대
이름              
사람1  30  서울  30대
사람2  25  대전  20대
홍길동  20  서울  20대

In [155]:
df2 = df2.reset_index()
df2

이름  나이  도시  나이대
0  사람1  30  서울  30대
1  사람2  25  대전  20대
2  홍길동  20  서울  20대

In [156]:
#나이대가 기준이라면, 비교를 위해 문자열을 숫자열로 바꾸기
#map(dict)형태로 값 치환
b = {'20대': 2, '30대':3}
df2['나이대'] = df2['나이대'].map(b)
df2

이름  나이  도시  나이대
0  사람1  30  서울    3
1  사람2  25  대전    2
2  홍길동  20  서울    2

In [157]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   이름      3 non-null      object
 1   나이      3 non-null      object
 2   도시      3 non-null      object
 3   나이대     3 non-null      int64 
dtypes: int64(1), object(3)
memory usage: 224.0+ bytes


12-6 pandas의 기본 연산 1 - Series

In [158]:
import pandas as pd
a = {'a': 10, 'b':20, 'c':30, 'd':40, 'e':50}
a

{'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}

In [159]:
#Series(dict)형태로 딕셔너리를 시리즈로 만들기
b = pd.Series(a)
b

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [160]:
type(b)

pandas.core.series.Series

In [161]:
d.shape

(5,)

In [162]:
#시리즈 간 연산
c = b / 10
c

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
dtype: float64

In [163]:
#정수타입으로 표현
c = b//10
c

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [164]:
type(c)

pandas.core.series.Series

In [165]:
c.shape

(5,)

In [166]:
#시리즈 간 연산은 같은 위치끼리 연산
d = b + c
d

a    11
b    22
c    33
d    44
e    55
dtype: int64

In [167]:
#index가 다른 경우
e = {'a':10, 'c':20, 'e':30, 'g':40}
e

{'a': 10, 'c': 20, 'e': 30, 'g': 40}

In [168]:
f = pd.Series(e)
f

a    10
c    20
e    30
g    40
dtype: int64

In [169]:
#둘다 있는 경우 연산, 한쪽만 있는 경우 NaN
d + f

a    21.0
b     NaN
c    53.0
d     NaN
e    85.0
g     NaN
dtype: float64

In [170]:
#한쪽에만 있는 것(결측치)은 add함수와 fill_value 활용
d.add(f, fill_value=0)

a    21.0
b    22.0
c    53.0
d    44.0
e    85.0
g    40.0
dtype: float64

In [171]:
#뺄셈
d.sub(f, fill_value=0)

a     1.0
b    22.0
c    13.0
d    44.0
e    25.0
g   -40.0
dtype: float64

In [172]:
#곱셈의 경우 0을 곱하면 0이므로 1로 해줘야 한다.
d.mul(f, fill_value=0)

a     110.0
b       0.0
c     660.0
d       0.0
e    1650.0
g       0.0
dtype: float64

In [173]:
d.mul(f, fill_value=1)

a     110.0
b      22.0
c     660.0
d      44.0
e    1650.0
g      40.0
dtype: float64

In [174]:
#나눗셈도 0 말고 1로 해야 됨
d.div(f, fill_value=0)

a    1.100000
b         inf
c    1.650000
d         inf
e    1.833333
g    0.000000
dtype: float64

In [175]:
d.div(f, fill_value=1)

a     1.100000
b    22.000000
c     1.650000
d    44.000000
e     1.833333
g     0.025000
dtype: float64

12-7 pandas의 기본 연산 2 - DataFrame 1

In [2]:
import pandas as pd

a = {'점수 1': [10,20,30], '점수 2': [20,40,60]}

df1 = pd.DataFrame(a)
df1

점수 1  점수 2
0    10    20
1    20    40
2    30    60

In [5]:
b = {'점수 1': [100,200,300], '점수 3': [200,400,600]}

df2 = pd.DataFrame(b)
df2

점수 1  점수 3
0   100   200
1   200   400
2   300   600

In [6]:
df3 = df1 + df2
df3
#같은 자리에 값이 있다면 계산이 잘 되지만
#다른 값이 있다면 연산 자체가 안 된다.

점수 1  점수 2  점수 3
0   110   NaN   NaN
1   220   NaN   NaN
2   330   NaN   NaN

In [7]:
#add함수 활용, fill_value=0으로 빈 칸을 0으로 채운다.
df4 = df1.add(df2, fill_value = 0)
df4

점수 1  점수 2   점수 3
0   110  20.0  200.0
1   220  40.0  400.0
2   330  60.0  600.0

In [8]:
#뺄셈의 경우도 마찬가지이다.
df5 = df1.sub(df2, fill_value=0)
df5

점수 1  점수 2   점수 3
0   -90  20.0 -200.0
1  -180  40.0 -400.0
2  -270  60.0 -600.0

In [9]:
#곱셈, 나눗셈의 경우 fill_value=1로 넣어야 한다.
df6 = df1.mul(df2, fill_value=1)
df6

점수 1  점수 2   점수 3
0  1000  20.0  200.0
1  4000  40.0  400.0
2  9000  60.0  600.0

In [10]:
df7 = df1.div(df2, fill_value=1)
df7

점수 1  점수 2      점수 3
0   0.1  20.0  0.005000
1   0.1  40.0  0.002500
2   0.1  60.0  0.001667

12-8 pandas의 기본 연산3 - DataFrame 2

In [11]:
a = {'이름': ['홍길동', '사람1', '사람2'], '나이': [20,30,25]}
df1 = pd.DataFrame(a)
df1

이름  나이
0  홍길동  20
1  사람1  30
2  사람2  25

In [12]:
b = {'이름': ['홍길동', '사람1', '사람2'], '도시': ['서울', '서울', '대전']}
df2 = pd.DataFrame(b)
df2

이름  도시
0  홍길동  서울
1  사람1  서울
2  사람2  대전

In [13]:
#merge : 합치기, how : 붙일 방향, left_on : 왼쪽 기준 컬럼
df = pd.merge(left = df1,
             right = df2,
             how = 'left',
             left_on = '이름',
             right_on = '이름')
df

이름  나이  도시
0  홍길동  20  서울
1  사람1  30  서울
2  사람2  25  대전

In [16]:
#조건식 사용, 불리안 활용, 원본은 바뀌지 않는다.
x1 = (df['도시'] == '서울')
df[x1]

이름  나이  도시
0  홍길동  20  서울
1  사람1  30  서울

In [17]:
x2 = (df['도시'] != '서울')
df[x2]

이름  나이  도시
2  사람2  25  대전

In [18]:
x3 = (df['나이'] < 30)
df[x3]

이름  나이  도시
0  홍길동  20  서울
2  사람2  25  대전

In [21]:
#조건 여러 개 달기 and(&), or(|)
x4 = (df['도시'] == '서울') & (df['나이'] < 30)
df[x4]

이름  나이  도시
0  홍길동  20  서울

In [22]:
x5 = (df['도시'] == '서울') | (df['나이'] < 30)
df[x5]

이름  나이  도시
0  홍길동  20  서울
1  사람1  30  서울
2  사람2  25  대전