## 11-1 Numpy의 1차원 자료형 1\
\
1차원적인 데이터 형식\
파이썬의 리스트와 유사하나, 벡터 연산이 가능함

In [1]:
import numpy as np

In [2]:
a = [10,20,30,40,50]

In [3]:
a

[10, 20, 30, 40, 50]

In [4]:
type(a)

list

In [5]:
#numpy의 array함수로 리스트를 불러오면 1차원 자료로 만들어준다.
b = np.array(a)

In [6]:
b

array([10, 20, 30, 40, 50])

In [7]:
print(b)

[10 20 30 40 50]


In [8]:
#shape 함수로 원소 개수, 차원 수를 알 수 있다.
b.shape

(5,)

In [9]:
c = np.array([5,4,3,2,1])

In [10]:
c

array([5, 4, 3, 2, 1])

In [11]:
#array의 덧셈은 같은 자리끼리 더해준다.
b + c

array([15, 24, 33, 42, 51])

In [12]:
#단순 수식은 각각에 더해준다.
b + 5

array([15, 25, 35, 45, 55])

In [13]:
#리스트에서는 이런 연산이 안 된다.
a + 5

TypeError: can only concatenate list (not "int") to list

In [14]:
#리스트에 리스트를 더하면 이어붙이기가 된다.
a + [5,4,3,2,1]

[10, 20, 30, 40, 50, 5, 4, 3, 2, 1]

11-2 numpy의 1차원 자료형 2\
\
자주 사용하는 numpy 기본 함수\
#sum(): 합계\
#mean(): 평균\
#max(): 최댓값\
#min(): 최솟값\
#round(): 반올림\
#arange(): 리스트의 range()와 유사\
#zeros(): 0으로 이루어진 벡터\
#ones(): 1로 이루어진 벡터\
#copy(): 복사

In [15]:
#sum 함수로 합계 구하기
np.sum(b)

150

In [17]:
#mean 함수로 평균 구하기
np.mean(b)

30.0

In [19]:
#max 함수로 최댓값 구하기
np.max(b)

50

In [20]:
#min 함수로 최솟값 구하기
np.min(b)

10

In [21]:
c

array([5, 4, 3, 2, 1])

In [22]:
b

array([10, 20, 30, 40, 50])

In [23]:
c = b/3

In [24]:
c

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667])

In [25]:
#round 함수로 반올림하기, 1은 소수점 첫째자리까지 반올림하라는 뜻
np.round(c, 1)

array([ 3.3,  6.7, 10. , 13.3, 16.7])

In [26]:
np.round(c, 3)

array([ 3.333,  6.667, 10.   , 13.333, 16.667])

In [27]:
np.round(c,0)

array([ 3.,  7., 10., 13., 17.])

In [29]:
#인덱스로 접근하기, 파이썬과 동일
b

array([10, 20, 30, 40, 50])

In [30]:
b[0]

10

In [31]:
b[1:3]

array([20, 30])

In [32]:
b[2:]

array([30, 40, 50])

In [33]:
np.sum(b[2:])

120

In [35]:
np.mean(b[2:])

40.0

In [36]:
#특정 위치 값 바꾸기도 파이썬과 동일
b[1] = 200

In [37]:
b

array([ 10, 200,  30,  40,  50])

In [38]:
#arange함수는 파이썬의 range와 유사하다
d = np.arange(5)

In [39]:
d

array([0, 1, 2, 3, 4])

In [40]:
e = np.arange(3,8)

In [41]:
e

array([3, 4, 5, 6, 7])

In [42]:
f = np.arange(3,8,2)

In [43]:
f

array([3, 5, 7])

In [44]:
#zeros 함수는 0으로 채우기, 개수 지정 가능
g = np.zeros(5)

In [45]:
g

array([0., 0., 0., 0., 0.])

In [46]:
#ones 함수는 1로 채우기, 개수 지정 가능
h = np.ones(5)

In [47]:
h

array([1., 1., 1., 1., 1.])

In [49]:
#단순복사와 copy 함수 활용
b

array([ 10, 200,  30,  40,  50])

In [50]:
bb = b
bb

array([ 10, 200,  30,  40,  50])

In [51]:
#값을 바꾸면 원본도 바뀐다.
bb[0] = 100
bb

array([100, 200,  30,  40,  50])

In [52]:
b

array([100, 200,  30,  40,  50])

In [53]:
#copy 활용
bb = b.copy()

In [54]:
bb[0] = 10

In [55]:
bb

array([ 10, 200,  30,  40,  50])

In [56]:
b

array([100, 200,  30,  40,  50])

11-3 numpy의 2차원 자료형\
\
2차원적인 데이터 형식\
행렬 연산이 가능함

In [57]:
import numpy as np

In [58]:
#대괄호 두 개면 2차원 형식
a = np.array([[10,20,30,40],[50,60,70,80]])

In [59]:
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [60]:
#행,열 순으로 나온다.
a.shape

(2, 4)

In [61]:
#각각 변수로 지정 가능
b, c = a.shape

In [62]:
b

2

In [63]:
c

4

In [64]:
#인덱스로 접근할 때 행,열 순으로 작성한다.
a[0,0]

10

In [65]:
a[-1,-1]

80

In [69]:
a[1,1:]

array([60, 70, 80])

In [70]:
#원본 보존
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [71]:
#값 바꾸기
a[0, 1] = 2

In [72]:
a

array([[10,  2, 30, 40],
       [50, 60, 70, 80]])

In [73]:
#zeros 함수 활용, 2차원 형식
b = np.zeros((2,4))

In [74]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [75]:
#ones 함수 활용, 3차원 형식
c = np.ones((3,5))

In [76]:
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [77]:
#reshape 함수 활용: 차원 바꾸기
c = np.arange(8)

In [78]:
c

array([0, 1, 2, 3, 4, 5, 6, 7])

In [79]:
c.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [80]:
#원본 보존
c

array([0, 1, 2, 3, 4, 5, 6, 7])

In [85]:
#저장하려면 변수 지정
c = c.reshape(2,4)

In [86]:
c

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [88]:
#또 형태를 바꿀 수 있음
c = c.reshape((4,2))

In [89]:
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [90]:
#차원에 상관 없이 전체 합계
c.sum()

28

In [103]:
#copy 함수 활용
d = c.copy()

In [104]:
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [105]:
d

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [106]:
d[0,0] = 10

In [107]:
d

array([[10,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7]])

In [108]:
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [109]:
c==d

array([[False,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [110]:
#arange 함수와 reshape 함수 한 번에 사용 가능
e = np.arange(49).reshape(7,7)

In [111]:
e

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [113]:
#특정 행,열을 가져오기
e[:,1:3]

array([[ 1,  2],
       [ 8,  9],
       [15, 16],
       [22, 23],
       [29, 30],
       [36, 37],
       [43, 44]])

In [116]:
e[3:,:4]

array([[21, 22, 23, 24],
       [28, 29, 30, 31],
       [35, 36, 37, 38],
       [42, 43, 44, 45]])

In [117]:
#특정 행,열의 합계 구하기
e[3:,:4].sum()

528

In [118]:
#특정 행,열만 가져와 새로운 행렬 만들기
f = e[3:, :4].copy()
f

array([[21, 22, 23, 24],
       [28, 29, 30, 31],
       [35, 36, 37, 38],
       [42, 43, 44, 45]])

In [119]:
#copy 함수를 사용했으므로 서로 영향을 주지 않는다.
e[4,0] = 100

In [120]:
e

array([[  0,   1,   2,   3,   4,   5,   6],
       [  7,   8,   9,  10,  11,  12,  13],
       [ 14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27],
       [100,  29,  30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39,  40,  41],
       [ 42,  43,  44,  45,  46,  47,  48]])

In [121]:
f

array([[21, 22, 23, 24],
       [28, 29, 30, 31],
       [35, 36, 37, 38],
       [42, 43, 44, 45]])

In [122]:
f.sum()

528

11-4 Numpy의 기본 연산과 조건 처리 1\
\
numpy의 기본 연산\
#사칙연산(+, -, *, /, //, %)\
#스칼라곱, 행렬곱

In [123]:
import numpy as np

In [124]:
a = np.arange(5,45,5).reshape(2,4)

In [125]:
b = np.arange(20,36,2).reshape(2,4)

In [126]:
a

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40]])

In [127]:
b

array([[20, 22, 24, 26],
       [28, 30, 32, 34]])

In [128]:
#두 행렬의 크기가 같으므로 사칙연산이 가능함
a + b

array([[25, 32, 39, 46],
       [53, 60, 67, 74]])

In [129]:
a - b

array([[-15, -12,  -9,  -6],
       [ -3,   0,   3,   6]])

In [130]:
b - a

array([[15, 12,  9,  6],
       [ 3,  0, -3, -6]])

In [131]:
a * b

array([[ 100,  220,  360,  520],
       [ 700,  900, 1120, 1360]])

In [132]:
a / b

array([[0.25      , 0.45454545, 0.625     , 0.76923077],
       [0.89285714, 1.        , 1.09375   , 1.17647059]])

In [133]:
# //는 나눠서 정수형태로 표시
a // b

array([[0, 0, 0, 0],
       [0, 1, 1, 1]], dtype=int32)

In [134]:
# 나머지 연산
a % b

array([[ 5, 10, 15, 20],
       [25,  0,  3,  6]], dtype=int32)

In [135]:
#행렬의 모든 값에 사칙연산
a * 10

array([[ 50, 100, 150, 200],
       [250, 300, 350, 400]])

In [136]:
#원본은 보존
a

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40]])

In [137]:
#변수 지정
c = a * 10

In [138]:
c

array([[ 50, 100, 150, 200],
       [250, 300, 350, 400]])

In [139]:
#형태가 다르면 연산이 안 된다.
b

array([[20, 22, 24, 26],
       [28, 30, 32, 34]])

In [140]:
bb = b.reshape(4,2)

In [141]:
bb

array([[20, 22],
       [24, 26],
       [28, 30],
       [32, 34]])

In [143]:
a

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40]])

In [145]:
#형태가 다르므로 곱이 안 된다.
a*bb

ValueError: operands could not be broadcast together with shapes (2,4) (4,2) 

In [144]:
# @ 기호를 활용하여 행렬곱이 가능하다.
a@bb

array([[1400, 1500],
       [3480, 3740]])

11-5 Numpy의 기본 연산과 조건 처리 2\
\
numpy의 조건 처리

In [147]:
a = np.arange(1,15)

In [148]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [149]:
#각각 bool 형태로 출력
a > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True])

In [150]:
a == 5

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False])

In [151]:
#참인 경우만 모아서 출력
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [152]:
#범위 지정과 값 수정
a[a<5] = 5

In [153]:
a

array([ 5,  5,  5,  5,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [154]:
a[a>10] = 10

In [155]:
a

array([ 5,  5,  5,  5,  5,  6,  7,  8,  9, 10, 10, 10, 10, 10])