In [1]:
import numpy as np
x = np.array([
    [0.1, 0.8, 0.1],
    [0.3, 0.1, 0.6],
    [0.2, 0.5, 0.3],
    [0.8, 0.1, 0.1]
])


In [2]:
y = np.argmax(x) 
#np.argmax(x)는 x 배열을 1차원으로 평면화된 배열에 대해 최대값을 갖는 인덱스를 반환

y0 = np.argmax(x, axis=0) 
#np.argmax(x, axis=0)는 첫번째 축인 row 방향(세로방향)으로 구성되는 요소 중 최대인 인덱스를 반환

y1 = np.argmax(x, axis=1) 
#y1 = np.argmax(x, axis=1)는 두번째 축인 column 방향(가로방향)으로 구성되는 요소 중 최대인 인덱스를 반환

print(y) # output: 1
print(y0) # output: [3 0 1]
print(y1) # output: [1 2 1 0]

1
[3 0 1]
[1 2 1 0]


In [3]:
y2 = np.argmax(x, axis=-1)
print(y2)

[1 2 1 0]
