In [1]:
import math
math.sin(1)


0.8414709848078965

In [2]:
math.cos(2)

-0.4161468365471424

In [3]:
math.tan(1)

1.5574077246549023

In [4]:
math.floor(2.6) #내림

2

In [5]:
math.ceil(2.4) #올림

3

#beautifulsoup 모듈로 날씨 가져오기

In [2]:
#모듈 읽어 들이기
from urllib import request
from bs4 import BeautifulSoup

#urlopen()함수로 기상청의 전국 날씨를 찾습니다.
target = request.urlopen("https://www.weather.go.kr/weather/forecast/mid-term_01.jsp")

#BeautifulSoup을 사용해 웹 페이지를 분석합니다.
soup = BeautifulSoup(target, "html.parser")

#location 태그를 찾습니다.

In [1]:
#content_weather > table:nth-child(9) > tbody > tr:nth-child(1) > th:nth-child(2)

In [3]:
list(range(10))
import numpy as np #numpy를 가져와서 np로 치환!!!
np.array([1,2,3,4,5])
np.array([3,1.4,2,3,4]) #실수가 하나라도 있으면 전부 실수로 변환
np.array([[1,2],
         [3,4]])
np.array([1,2,3,4], dtype='float') #아예 실수로 변환

array([1., 2., 3., 4.])

In [4]:
arr = np.array([1,2,3,4], dtype=float) #float로 바꾸기
arr #float로 출력
arr.dtype #float type으로 표시
arr.astype(int) #타입 int로 변경

array([1, 2, 3, 4])

In [5]:
np.zeros(10, dtype=int)
np.ones((3,5), dtype=float)
np.arange(0,20,2) #0부터 20-1까지 2칸씩 띄어라
np.linspace(0,1,5) #0부터 1까지 5등분해라. 매우 유용!


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [6]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.random.random((2,2)) #2,2짜리 랜덤함수 출력


array([[0.48592313, 0.13630197],
       [0.31701828, 0.76744098]])

In [10]:
np.random.normal(0,1,(2,2))

array([[ 1.51699946, -0.33895482],
       [-1.68379409,  0.1510547 ]])

In [12]:
np.random.randint(0,10,(3,2)) #0부터 10까지 3행2열로 int타입 출력

array([[5, 9],
       [0, 1],
       [7, 3]])