In [4]:
#numpy: C언어로 구현된 파이썬 라이브러리, 수치 계산용. 딥러닝에서 많이 씀
import numpy as np


In [21]:
nd1 = np.array([1,2,3,4])
nd1


array([1, 2, 3, 4])

In [22]:
type(nd1)

numpy.ndarray

In [23]:
#1차원 표현
nd1.ndim

1

In [24]:
nd1.shape

(4,)

In [25]:
nd1.size

4

In [16]:
nd1.shape # (4,1) 4행, 1열로 이루어져 있다는 뜻
#nd2.shape (2,3)
#nd3.shape (2,4,3)
#nd4.shape (3,2,2,2)

(4,)

In [13]:
type(nd1)

numpy.ndarray

In [27]:
nd2 = np.array([[1,2,3], [4,5,6]]) #행/열 구조로 표현하기 위해 대괄호로 묶어준다
print(nd2) #2차원 모양으로 전체 출력
print(nd2.ndim) #차원 확인 number of dimention
print(type(nd2))
print(nd2.shape)#모양 확인하여 (열, 행)으로 표현
print(nd1.size)#전체 개수
#2차원 읽는 순서는 0,0 0,1 0,2
                  #1,0 1,1 1,2 이런 식으로 순서대로 간다.

[[1 2 3]
 [4 5 6]]
2
<class 'numpy.ndarray'>
(2, 3)
4


In [11]:
#ndarray 객체는 차원(ndim), 자료형(dtype), 모양(shape), 크기(size)
#차원을 바꿀 때는 reshape()함수를 사용

In [15]:
#dtype = 'np.float32'
#dtype = 'float64'
#nd1 = dn1.astype(np.int32)

In [32]:
print(np.zeros((4,3))) #0으로 채우기
print(np.ones((3,4))) #1로 채우기

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [34]:
a = np.ones((3,4))
a.size

12

In [35]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [37]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [38]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [42]:
np.arange(1200).reshape(4,-1)#끝자리 자동계산 -1

array([[   0,    1,    2, ...,  297,  298,  299],
       [ 300,  301,  302, ...,  597,  598,  599],
       [ 600,  601,  602, ...,  897,  898,  899],
       [ 900,  901,  902, ..., 1197, 1198, 1199]])

In [1]:
from urllib import request
from bs4 import BeautifulSoup

target = request.urlopen("http://www.kma.go.kr/weather/forecast/mid-term-rss3.jsp?stnId=108")

soup = BeautifulSoup(target, "html.parser")

for location in soup.select("location"):
    print("도시:", location.select_one("city").string)
    print("날씨:", location.select_one("wf").string)
    print("최저기온:", location.select_one("tmn").string)
    print("최고기온:", location.select_one("tmx").string)
    print()


도시: 서울
날씨: 맑음
최저기온: 7
최고기온: 17

도시: 인천
날씨: 맑음
최저기온: 8
최고기온: 15

도시: 수원
날씨: 맑음
최저기온: 5
최고기온: 17

도시: 파주
날씨: 맑음
최저기온: 2
최고기온: 17

도시: 이천
날씨: 맑음
최저기온: 2
최고기온: 18

도시: 평택
날씨: 맑음
최저기온: 4
최고기온: 18

도시: 춘천
날씨: 맑음
최저기온: 2
최고기온: 19

도시: 원주
날씨: 맑음
최저기온: 4
최고기온: 19

도시: 강릉
날씨: 맑음
최저기온: 5
최고기온: 17

도시: 대전
날씨: 맑음
최저기온: 5
최고기온: 19

도시: 세종
날씨: 맑음
최저기온: 4
최고기온: 18

도시: 홍성
날씨: 맑음
최저기온: 3
최고기온: 17

도시: 청주
날씨: 맑음
최저기온: 6
최고기온: 19

도시: 충주
날씨: 맑음
최저기온: 2
최고기온: 18

도시: 영동
날씨: 맑음
최저기온: 2
최고기온: 19

도시: 광주
날씨: 맑음
최저기온: 7
최고기온: 19

도시: 목포
날씨: 맑음
최저기온: 8
최고기온: 17

도시: 여수
날씨: 맑음
최저기온: 9
최고기온: 15

도시: 순천
날씨: 맑음
최저기온: 6
최고기온: 17

도시: 광양
날씨: 맑음
최저기온: 7
최고기온: 17

도시: 나주
날씨: 맑음
최저기온: 5
최고기온: 18

도시: 전주
날씨: 맑음
최저기온: 5
최고기온: 19

도시: 군산
날씨: 맑음
최저기온: 4
최고기온: 17

도시: 정읍
날씨: 맑음
최저기온: 5
최고기온: 18

도시: 남원
날씨: 맑음
최저기온: 3
최고기온: 19

도시: 고창
날씨: 맑음
최저기온: 4
최고기온: 18

도시: 무주
날씨: 맑음
최저기온: 2
최고기온: 18

도시: 부산
날씨: 맑음
최저기온: 8
최고기온: 16

도시: 울산
날씨: 맑음
최저기온: 5
최고기온: 15

도시: 창원
날씨: 맑음
최저기온: 6
최고기온: 16

도시: 진주
날씨: 맑음
최저기온: 3
최고기온: 17

도시: 거창
날

In [5]:
from flask import Flask

app = Flask(__name__)

@app.route("/")
def hello():
    return "<h1> Hi, gayeon </h1>"

In [6]:
from flask import Flask
from urllib import request
from bs4 import BeautifulSoup

app = Flask(__name__)

@app.route("/")

def hello():
    
    target = request.urlopen("http://www.kma.go.kr/weather/forecast/mid-term-rss3.jsp?stnId=108")

    soup = BeautifulSoup(target, "html.parser")
    
    output = ""
    for location in soup.select("location"):
        output += "<h3>{}</h3>".format(location.select_one("city").string)
        output += "날씨: <br>{}</br>".format(location.select_one("wf").string)
        output += "최저/최고 기운: {}/{}".format(location.select_one("tmn").string,
                                                 location.select_one("tmx").string)
        output += "<hr/>"
    return output


In [7]:
from flask import Flask 
from urllib import request 
from bs4 import BeautifulSoup

app = Flask(__name__)

@app.route("/")

def hello():
    
    target = request.urlopen("http://www.kma.go.kr/weather/forecast/mid-term-rss3.jsp?stnId=108")

    soup = BeautifulSoup(target, "html.parser")
    
    output =""
    for location in soup.select("location"):
        output +="<h3>{}</h3>".format(location.select_one("city").string)
        output +="날씨: <br>{}</br>".format(location.select_one("wf").string)
        output +="최저/최고 기온:{}/{}".format(location.select_one("tmn").string,
                                               location.select_one("tmx").string)
        output += "<hr/>"
    return output        

In [8]:
from math import *

In [9]:
print(sin(1))
print(cos(1))
print(tan(1))

0.8414709848078965
0.5403023058681398
1.5574077246549023
