In [1]:
import numpy as np

In [9]:
np.array([])

array([], dtype=float64)

In [15]:
x2 = np.random.randint(10, size=(3,4)) #10-1까지 3,4사이즈로 배열 생성
x2

array([[7, 0, 2, 9],
       [8, 4, 8, 3],
       [2, 3, 9, 0]])

In [16]:
x2.ndim #2
x2.shape #(3,4)
x2.size #12
x2.dtype #dtype('int64')

dtype('int32')

In [18]:
x = np.arange(7)
x

array([0, 1, 2, 3, 4, 5, 6])

In [19]:
x[3] #list 처럼 index로 접근

3

In [20]:
x[1] = 7 #index에 value 넣을 수 있음
x

array([0, 7, 2, 3, 4, 5, 6])

In [23]:
x[1]

7

In [26]:
x = np.arange(7)
x[1:4]

array([1, 2, 3])

In [30]:
x[0:7:2] #0부터 7-1까지 2칸씩 띄어라

array([0, 2, 4, 6])

In [31]:
x[::2] #전체를 가져오고 step 2

array([0, 2, 4, 6])

In [36]:
x = np.arange(8) #1차원이기 때문에
x.shape #8행 1열로 나옴
x #array([0,1,2,3,4,5,6,7])

array([0, 1, 2, 3, 4, 5, 6, 7])

In [34]:
x2 = x.reshape((2,4)) #x를 reshape하여 2차원으로 표현하였으므로
x2.shape #2행 4열로 나옴
x2 #array([[0,1,2,3], [4,5,6,7]])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [42]:
x4 = x2.reshape(2,2,2,1)
x4.shape
x4

array([[[[0],
         [1]],

        [[2],
         [3]]],


       [[[4],
         [5]],

        [[6],
         [7]]]])

In [43]:
x = np.array([0,1,2])
y = np.array([3,4,5])
np.concatenate([x,y]) #concatenate()로 두 배열 합침!!!! 헷갈리면 shift+tab
#np.concatenate: axit 축을 기준으로 이어붙임

array([0, 1, 2, 3, 4, 5])

In [46]:
mat = np.arange(4) #1차원 배열 만들기
mat

array([0, 1, 2, 3])

In [47]:
mat = np.arange(4).reshape(2,2) #2차원으로 변형하기
mat

array([[0, 1],
       [2, 3]])

In [49]:
np.concatenate([mat,mat], axis=0) #axis는 행 기준으로 한다는 뜻.


array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3]])

In [50]:
np.concatenate([mat,mat], axis=1) #axis = 1이면 열이 늘어난다.

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

In [51]:
#이어붙이고 나누기
mat1 = np.arange(4)
mat1

array([0, 1, 2, 3])

In [58]:
mat1 = np.arange(16).reshape(4,4)
mat1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
np.concatenate([mat1,mat1], axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [60]:
upper, lower = np.split(mat1, [2], axis=0) #mat1을 2행 기준으로 자르기

In [61]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [62]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [67]:
left, right = np.split(mat1, [2], axis=1) #mat1을 2열 기준으로 자르기

In [68]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [69]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [71]:
def add_five_to_array(values): #values를 넣는 함수를 선언
    output = np.empty(len(values)) #변수를 선언하여 values 길이만큼 빈 공간 생성
    for i in range(len(values)): #values의 길이만큼 반복문 선언
        output[i] = values[i] + 5 #빈 공간의 i번째에 values i번째+5를 넣음
    return output #결과를 빈 공간에 저장

values = np.random.randint(0,10,size=5) #values 값을 randint로 지정
add_five_to_array(values)

array([10., 14.,  7., 12., 13.])

In [72]:
np.empty([2,2]) #empty는 빈 공간을 만들어 놓는 것, zeros와 달리 값이 있긴 함.

array([[2.12199579e-314, 3.81388228e+180],
       [2.96439388e-321, 9.84606047e-312]])

In [75]:
x = np.arange(4)
x + 5 #배열에 사칙연산 가능

array([5, 6, 7, 8])

In [76]:
x - 5

array([-5, -4, -3, -2])

In [78]:
x * 5

array([ 0,  5, 10, 15])

In [79]:
x / 5

array([0. , 0.2, 0.4, 0.6])

In [86]:
x = np.arange(4).reshape((2,2))
x

array([[0, 1],
       [2, 3]])

In [87]:
y = np.random.randint(10)
y

9

In [88]:
y = np.random.randint(10, size=(2,2))
y

array([[2, 3],
       [0, 6]])

In [89]:
x + y #배열 간 사칙연산 가능

array([[2, 4],
       [2, 9]])

In [90]:
x - y

array([[-2, -2],
       [ 2, -3]])

In [91]:
np.arange(3) #실제로는 3행 1열이다!!!!!!!!!!!!

array([0, 1, 2])

In [92]:
np.arange(3).reshape((3,1))

array([[0],
       [1],
       [2]])

In [93]:
np.arange(3).reshape((3,1)) + np.arange(3) #연장해버리기

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [94]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [96]:
x = np.arange(8).reshape((2,4))
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [97]:
np.sum(x) #각각의 원소의 총합

28

In [99]:
np.min(x) #원소의 최솟값

0

In [101]:
np.max(x) #원소의 최댓값

7

In [102]:
np.mean(x) #mean()는 평균값 구하는 함수

3.5

In [109]:
x = np.zeros(8)
x

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [110]:
y = np.ones(8)
y

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [117]:
np.concatenate((x,y))

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.])

In [119]:
x = np.arange(8).reshape(2,4)
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [120]:
np.sum(x, axis=0) #행 기준으로 잘라서 더한다. 결국 각 열의 합

array([ 4,  6,  8, 10])

In [123]:
np.sum(x,axis=1) #열 기준으로 잘라서 더한다. 결국 각 행의 합

array([ 6, 22])

In [124]:
x = np.arange(8)
x[x<3]

array([0, 1, 2])

In [125]:
x>3

array([False, False, False, False,  True,  True,  True,  True])

In [126]:
#pandas
import pandas as pd

pd.Series([1,2,3,4]) #index와 data가 같이 들어가있음.

0    1
1    2
2    3
3    4
dtype: int64

In [127]:
pd.Series([1,2,3,4], index = ['a','b','c','d']) #index name을 지정

a    1
b    2
c    3
d    4
dtype: int64

In [128]:
data = pd.Series([1,2,3,4], index = ['a','b','c','d'])

In [129]:
data

a    1
b    2
c    3
d    4
dtype: int64

In [130]:
data['b'] #index b자리의 데이터 출력

2

In [131]:
data.b #이거 되긴 하는데 딕셔너리마냥 ['b']형태로 하는 게 좋음

2

In [140]:
data2 = pd.Series([1,2,3,4,5], index = ['수','우','미','양','가'],
                  name = "love")
data2

수    1
우    2
미    3
양    4
가    5
Name: love, dtype: int64

In [134]:
data2['우']

2

In [136]:
data2.우

2

In [137]:
def 교수():
    print("닥터윌")

In [139]:
교수()

닥터윌


In [173]:
#딕셔너리로 변환
population_dict = {
    'korea': 5180,
    'japan': 12718,
    'china': 141500,
    'usa': 32676
}

population = pd.Series(population_dict, name = "세계 인구")
population
#Series는 키와 값을 다 보여주는 함수

korea      5180
japan     12718
china    141500
usa       32676
Name: 세계 인구, dtype: int64

In [199]:
gdp_dict = {
'korea': 169320000,
'japan': 516700000,
'china': 1409250000,
'usa': 2041280000,
}

gdp = pd.Series(gdp_dict)
gdp

korea     169320000
japan     516700000
china    1409250000
usa      2041280000
dtype: int64

In [245]:
country = pd.DataFrame({
    'popu': population,
    'gd': gdp
    
})

In [246]:
country

popu          gd
korea    5180   169320000
japan   12718   516700000
china  141500  1409250000
usa     32676  2041280000

In [247]:
country.index

Index(['korea', 'japan', 'china', 'usa'], dtype='object')

In [248]:
country.columns

Index(['popu', 'gd'], dtype='object')

In [249]:
country['gd']

korea     169320000
japan     516700000
china    1409250000
usa      2041280000
Name: gd, dtype: int64

In [250]:
type(country['gd'])

pandas.core.series.Series

In [251]:
###########이거 모르면 취업 못 함. 엔트리 레벨 때 하는 일############
gdp_per_capital = country['gd'] / country['popu']
country["gdp_per_capital"] = gdp_per_capital


In [252]:
country

popu          gd  gdp_per_capital
korea    5180   169320000     32687.258687
japan   12718   516700000     40627.457147
china  141500  1409250000      9959.363958
usa     32676  2041280000     62470.314604

In [253]:
country.to_csv("./country.csv")#./는 같은 폴더에 저장. 직접 지정도 가능
country.to_csv("./country.xlsx")

In [254]:
pd.read_csv("./country.csv")

Unnamed: 0    popu          gd  gdp_per_capital
0      korea    5180   169320000     32687.258687
1      japan   12718   516700000     40627.457147
2      china  141500  1409250000      9959.363958
3        usa   32676  2041280000     62470.314604

In [255]:
pd.read_csv("./country.xlsx")

Unnamed: 0    popu          gd  gdp_per_capital
0      korea    5180   169320000     32687.258687
1      japan   12718   516700000     40627.457147
2      china  141500  1409250000      9959.363958
3        usa   32676  2041280000     62470.314604

In [256]:
country

popu          gd  gdp_per_capital
korea    5180   169320000     32687.258687
japan   12718   516700000     40627.457147
china  141500  1409250000      9959.363958
usa     32676  2041280000     62470.314604

In [257]:
country.popu

korea      5180
japan     12718
china    141500
usa       32676
Name: popu, dtype: int64

In [258]:
type(country.popu)

pandas.core.series.Series

In [259]:
#loc는 location, iloc는 index location의 약자. iloc를 많이 씀

In [260]:
country.iloc[0]

popu               5.180000e+03
gd                 1.693200e+08
gdp_per_capital    3.268726e+04
Name: korea, dtype: float64

In [354]:
country.iloc[1:3, :2] #열, 행 순서로 가져옴

popu          gd
japan   12718   516700000
china  141500  1409250000

In [355]:
dataframe = pd.DataFrame(columns=['이름','나이','주소;'])
dataframe

Empty DataFrame
Columns: [이름, 나이, 주소;]
Index: []

In [356]:
dataframe.loc[0] = ['김가연','24','서울'] #list 형태로 series 값 넣어줌
dataframe

이름  나이 주소;
0  김가연  24  서울

In [357]:
dataframe = pd.DataFrame(columns=['이름','나이','주소'])
dataframe.loc[0] = ['양진욱','26','서울'] # 리스트 형태로  series 값 넣어줌
dataframe.loc[1] = {'이름':'안철수', '나이':'45', '주소':'인천'} # 딕셔너리 형태로 해당 값 넣어줌
dataframe

이름  나이  주소
0  양진욱  26  서울
1  안철수  45  인천

In [358]:
dataframe.loc[2, '이름'] = '트둥이'
dataframe

이름   나이   주소
0  양진욱   26   서울
1  안철수   45   인천
2  트둥이  NaN  NaN

In [359]:
dataframe.loc[3] = {'이름':'김태리', '나이':'22', '주소': '서울'}
dataframe

이름   나이   주소
0  양진욱   26   서울
1  안철수   45   인천
2  트둥이  NaN  NaN
3  김태리   22   서울

In [360]:
dataframe['전화번호'] = np.nan
dataframe['전화번호']

0   NaN
1   NaN
2   NaN
3   NaN
Name: 전화번호, dtype: float64

In [361]:
dataframe

이름   나이   주소  전화번호
0  양진욱   26   서울   NaN
1  안철수   45   인천   NaN
2  트둥이  NaN  NaN   NaN
3  김태리   22   서울   NaN

In [362]:
dataframe.loc[3, '전화번호'] = '01012345678'
dataframe

이름   나이   주소         전화번호
0  양진욱   26   서울          NaN
1  안철수   45   인천          NaN
2  트둥이  NaN  NaN          NaN
3  김태리   22   서울  01012345678

In [363]:
len(dataframe)

4

In [364]:
dataframe["이름"]

0    양진욱
1    안철수
2    트둥이
3    김태리
Name: 이름, dtype: object

In [365]:
dataframe[['이름','주소']] #2차원으로 표현

이름   주소
0  양진욱   서울
1  안철수   인천
2  트둥이  NaN
3  김태리   서울

In [366]:
dataframe

이름   나이   주소         전화번호
0  양진욱   26   서울          NaN
1  안철수   45   인천          NaN
2  트둥이  NaN  NaN          NaN
3  김태리   22   서울  01012345678

In [367]:
dataframe.isnull() #isnull은 없는 값인지 확인

이름     나이     주소   전화번호
0  False  False  False   True
1  False  False  False   True
2  False   True   True   True
3  False  False  False  False

In [368]:
dataframe.notnull() #notnull은 있는 값인지 확인

이름     나이     주소   전화번호
0  True   True   True  False
1  True   True   True  False
2  True  False  False  False
3  True   True   True   True

In [369]:
dataframe.dropna() #dropna()는 지금 활용할 수 없는 데이터 싹 없애기 명령
#dataframe의 전화번호 칸에 전화번호가 없을 시 fillna()안에 있는 거로 채우기
dataframe.전화번호 = dataframe.전화번호.fillna('전화번호 없음')
dataframe.나이 = dataframe.나이.fillna('나이 불명')
dataframe.주소 = dataframe.주소.fillna('주소지 불명')
dataframe

이름     나이      주소         전화번호
0  양진욱     26      서울      전화번호 없음
1  안철수     45      인천      전화번호 없음
2  트둥이  나이 불명  주소지 불명      전화번호 없음
3  김태리     22      서울  01012345678

In [370]:
dataframe2 = dataframe.dropna()

In [371]:
dataframe2

이름     나이      주소         전화번호
0  양진욱     26      서울      전화번호 없음
1  안철수     45      인천      전화번호 없음
2  트둥이  나이 불명  주소지 불명      전화번호 없음
3  김태리     22      서울  01012345678

In [372]:
x = pd.DataFrame(columns=['이름','나이','주소'])
x.loc[0] = '김가연', '24', '서울'
x.loc[1] = '강희찬', '29', '서울'
x.loc[2,'이름'] = '강경연'
x.loc[3,'나이'] = '22'
x.loc[4,'주소'] = '서울'
x.loc[5] = ''
x.dropna()
x.이름 = x.이름.fillna('불명')
x.나이 = x.나이.fillna('불명')
x.주소 = x.주소.fillna('불명')
x

이름  나이  주소
0  김가연  24  서울
1  강희찬  29  서울
2  강경연  불명  불명
3   불명  22  불명
4   불명  불명  서울
5

In [375]:
dataframe.loc[3,'전화번호'] = '전화번호 없음'
dataframe

이름     나이      주소     전화번호
0  양진욱     26      서울  전화번호 없음
1  안철수     45      인천  전화번호 없음
2  트둥이  나이 불명  주소지 불명  전화번호 없음
3  김태리     22      서울  전화번호 없음

In [392]:
dataframe.loc[2,'나이'] = 0
df = dataframe
df


이름  나이      주소     전화번호
0  양진욱  26      서울  전화번호 없음
1  안철수  45      인천  전화번호 없음
2  트둥이   0  주소지 불명  전화번호 없음
3  김태리  20      서울  전화번호 없음

In [394]:
#nan을 0으로 대체함
df_나이 = df['나이']
df_나이 = df.나이.fillna(0) #nan을 0으로 바꿔라
df_나이

0    26
1    45
2     0
3    20
Name: 나이, dtype: object

In [398]:
df_나이 = df_나이.astype(int)

In [399]:
df_나이.sum()

91

In [401]:
df_나이.mean()

22.75

In [410]:
#dataframe 연산 add(+), sub(-), mul(*), div(/)
import numpy as np
import pandas as pd

print("A: ")
A = pd.DataFrame(np.random.randint(0,10, (2,2)), columns=['A', 'B'])
print(A, "\n")

print("B: ")
B = pd.DataFrame(np.random.randint(0,10, (3,3)), columns=['B', 'A', 'C'])
print(B, "\n")

#연산 적용

A + B
A.add(B, fill_value=0) #A와 B를 합치고 빈 공간은 0으로 치환

A: 
   A  B
0  6  8
1  7  6 

B: 
   B  A  C
0  9  8  5
1  0  7  0
2  3  9  2 



A     B    C
0  14.0  17.0  5.0
1  14.0   6.0  0.0
2   9.0   3.0  2.0