회귀 문제 => mse

분류 문제 => cross entropy

In [8]:
import numpy as np
import pandas as pd

from nltk.corpus import stopwords
import string
import nltk

In [9]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/강의코드/6.24강의코드/spam.csv')
df.drop('Unnamed: 0', axis=1, inplace=True)

In [12]:
df

num label                    text  label_num
0    1  spam       your free lottery          1
1    2  spam  free lottery free you           1
2    3   ham        your free apple           0
3    4   ham     free to contact me           0
4    5   ham             I won award          0
5    6  spam      my lottery ticket           1

In [15]:
# 자연어 처리에서 유용한 코드!

def process_text(text):

  # text에서 구두점(punctuation)을 제거
  nopunc = [char for char in text if char not in string.punctuation] # text에서 하나씩 뽑아서 char에 넣고 char에 구두점이 없다면 nopunc에 넣어라
  nopunc = ''.join(nopunc)

  # text에서 불용어 제거
  cleaned_words = [word for word in nopunc.split()
                  if word.lower() not in stopwords.words('english')]

  return cleaned_words

In [16]:
df['text'].head()

0         your free lottery
1    free lottery free you 
2          your free apple 
3       free to contact me 
4               I won award
Name: text, dtype: object

In [20]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [21]:
df['text'].apply(process_text)

0          [free, lottery]
1    [free, lottery, free]
2            [free, apple]
3          [free, contact]
4                  [award]
5        [lottery, ticket]
Name: text, dtype: object

In [22]:
# 행렬 변환

from sklearn.feature_extraction.text import CountVectorizer # count를 세어서 vector를 뽑아주는 패키지
msg_bow = CountVectorizer(analyzer = process_text).fit_transform(df['text']) # 한 번에 단어주머니(back of word)를 만들었다.


In [23]:
msg_bow

<6x6 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [25]:
# data split (train : 80%, test : 20%)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(msg_bow, df['label_num'], test_size=0.2, random_state=0)

In [26]:
# 다항식 나이브메이즈 모델 훈련

from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [29]:
classifier.predict(X_test)

array([1, 1])

In [30]:
y_test.values

array([1, 0])

In [31]:
# 모델 정확도 

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix, accuracy_score


In [33]:
pred = classifier.predict(X_train) # 모델에 관한 예측 값 출력
pred

array([1, 0, 1, 0])